import { createRequire } from 'node:module'
import { pathToFileURL } from 'node:url'
import { readFile } from 'node:fs/promises'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const releasePath = join(__dirname, '..', 'build', 'release.js')

const mod = await import(pathToFileURL(releasePath).href)

export const {
  memory,
  newLazyCheckRangeStore,
  lazySetCheckedRange,
  lazyGetCheckedPoint,
  lazyGetRangeCount,
  clearLazyCheckedRanges,
  newTree,
  newTreeWithKeys,
  setTree,
  setNeighborTree,
  setMpttTree,
  getSize,
  getShownNodes,
  getAllNodes,
  getCompactMemoryBytes,
  getCompactMirrorBytes,
  getObjectStringPayloadBytes,
  canUseLazyCheckboxRange,
  setUseCompactSelection,
  setUseLazyCheckboxRanges,
  setUseSearchCandidateIndex,
  setUsePreorderedNeighborInput,
  getShownIndices,
  getNodeSelectionStates,
  getNodeLayouts,
  getAllNodeIds,
  getAllNodeLayouts,
  getInputNodeLayouts,
  clearInputNodeLayouts,
  getCheckedNodes,
  getCheckedIds,
  getCheckedIdList,
  switchDisplayTree,
  clear,
  popNeighbor,
  pushNeighborNode,
  pushNeighborNodes,
  pushNeighborNodesUtf8,
  popMptt,
  pushMpttNode,
  setBoundary,
  fuzzyTree,
  checkNode,
  clearCheckedNodes,
  setCheckedNode,
  setCheckedNodes,
  getShownHeight,
  collapseTree,
  setCheckedOutputMode,
  updateNodeName,
  appendChild,
  removeSubtree,
  beginStructureBatch,
  endStructureBatch,
  CheckType,
  SelectType,
  DisplayType,
  TreeFieldKeys,
  CheckedOutputMode,
} = mod
